services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: train-monitor
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
            - REDIS_HOST=redis

    redis:
        image: redis:latest
        container_name: train-monitor-redis
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
